# Generated by Django 6.0.6 on 2026-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('OUT_OF_STOCK', 'Out of Stock Alert'), ('PURCHASE_ORDER', 'Purchase Order Received'), ('SALE', 'New Sale Completed'), ('PAYMENT', 'Payment Received'), ('CUSTOMER', 'New Customer Added')], max_length=50),
        ),
    ]
